### PR TITLE
added new limit for number of contigs from single genbank file which …

### PR DESCRIPTION
**Pull request by realmarcin**
…currently get split into separate genbank files

the limit is 1000 and only the first 1000 will be uploaded if there are > 1000

### CODE REVIEW

**Comment by mlhenderson** [comment]
Is this addressing a specific ticket?

**Comment by realmarcin** [comment]
yes

https://atlassian.kbase.us/browse/KBASE-3781?filter=10930

**Comment by realmarcin** [comment]
BTW I also double-checked the splitting code -- file handles are definitely closed. It is reading and writing line by line but this should still be fairly quick. I'm not sure where the 3 hour runtime is coming from. I'll try to test it with Dan O's genome

**Comment by mlhenderson** [comment]
I'm going to merge this to get the bugfix in for the notes field (which is clearly not the title of this PR), but we need to revisit git branching to split these issues into separate PRs.

**Pull request merged**
