### PR TITLE
Added transformation scripts to support Communities' downloads.

### PR DESCRIPTION
**Pull request by jaredbischof**

### CODE REVIEW

**Comment by sjyoo** [comment]
Thanks for pull requests... 

Could you update your pull request to include the following changes?

  1) Download objects from WS instead of input file object 
     The typed object may have reference object and those stuff make us difficult to support the input json object conversion scripts... 

  2) Follow naming conventions:
     https://docs.google.com/document/d/1nwHL6I6twSYelPaC7x-jqYoQW-zQbCoXzIK_1_QzkPY/edit

  3) Add example data and test script in transform/t
     if possible, please create your directory under transform/t/your_type

**Comment by olsonanl** [comment]
Chris, I thought these scripts were using local files and that the infrastructure was downloading the input for us.

It’s the transform script’s job to do any json conversion - that’s what it is for.

For my part I don’t know offhand how to get example data. I’m going to the ws browser now to attempt to get a raw genome object; wish me luck.

—bob

On Jan 14, 2015, at 2:23 PM, sjyoo <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for pull requests...

Could you update your pull request to include the following changes?

1) Download objects from WS instead of input file object
The typed object may have reference object and those stuff make us difficult to support the input json object conversion scripts...

2) Follow naming conventions:
https://docs.google.com/document/d/1nwHL6I6twSYelPaC7x-jqYoQW-zQbCoXzIK_1_QzkPY/edit

3) Add example data and test script in transform/t
if possible, please create your directory under transform/t/your_type

**Comment by olsonanl** [comment]
Shinjae,

Please supply an example download script with the desired syntax for input arguments ASAP, and we will attempt to conform to it.
We would like to help provide transform scripts for download, but a lack of any example is completely blocking us.

Bob,

I will add code to ScriptHelpers.pm to manage all workspace interaction as soon as Shinjae sends his example.

A raw genome is attached.

Chris

**Comment by olsonanl** [comment]
I think Matt will send out the overall flow soon…

The following should be reasonable :

trns_transform_KBTYPE-to-EXTTYPE.pl -w workspace_name -i input_object_name -o output_file_name [-u ws_url]  [-s shock_url] [-h handle_url]
where the bracket options [-u ws_url] are optional.

If it generate multiple files, then “-o out_directory” and put your files in the directory…

Once it is done, download_hndlr will compress them and upload to shock. (out_file_name.zip or out_directory.zip)

Thanks,
-SJ


On Jan 14, 2015, at 4:17 PM, Christopher Henry <chrisshenry@gmail.com<mailto:chrisshenry@gmail.com>> wrote:

Shinjae,

Please supply an example download script with the desired syntax for input arguments ASAP, and we will attempt to conform to it.
We would like to help provide transform scripts for download, but a lack of any example is completely blocking us.

Bob,

I will add code to ScriptHelpers.pm to manage all workspace interaction as soon as Shinjae sends his example.

A raw genome is attached.

Chris



On Jan 14, 2015, at 2:29 PM, Olson, Robert D. <olson@mcs.anl.gov<mailto:olson@mcs.anl.gov>> wrote:

> Chris, I thought these scripts were using local files and that the infrastructure was downloading the input for us.
>
> It’s the transform script’s job to do any json conversion - that’s what it is for.
>
> For my part I don’t know offhand how to get example data. I’m going to the ws browser now to attempt to get a raw genome object; wish me luck.
>
> —bob
>
>> On Jan 14, 2015, at 2:23 PM, sjyoo <notifications@github.com<mailto:notifications@github.com>> wrote:
>>
>> Thanks for pull requests...
>>
>> Could you update your pull request to include the following changes?
>>
>> 1) Download objects from WS instead of input file object
>> The typed object may have reference object and those stuff make us difficult to support the input json object conversion scripts...
>>
>> 2) Follow naming conventions:
>> https://docs.google.com/document/d/1nwHL6I6twSYelPaC7x-jqYoQW-zQbCoXzIK_1_QzkPY/edit
>>
>> 3) Add example data and test script in transform/t
>> if possible, please create your directory under transform/t/your_type
>>
>> —
>> Reply to this email directly or view it on GitHub.
>>
>

<Rhodobacter_CACIA_14H1_contigs.2.json>

**Comment by olsonanl** [comment]
my scripts now use -i / -w to take the workspace obj id and workspace name and downloads the data properly, just using the workspace client API.

--bob

________________________________

**Comment by jaredbischof** [comment]
We have multiple transformations that can use the same script.  For this, doesn't it make sense to simply define in the config file the script to use for each transformation rather than copying an identical script over and over to have one for each different transformation?

**Comment by sjyoo** [comment]
We can still use the same script…

As long as you provide clear examples and test cases, it should be trivial…

Thanks,
-SJ

On Jan 15, 2015, at 12:58 PM, Jared Bischof <notifications@github.com<mailto:notifications@github.com>> wrote:


We have multiple transformations that can use the same script. For this, doesn't it make sense to simply define in the config file the script to use for each transformation rather than copying an identical script over and over to have one for each different transformation?

**Pull request merged**
