### PR TITLE
Initial addition of uploader for GFF to GenomeAnnotation

### PR DESCRIPTION
**Pull request by samseaver**
Don't merge this, I'm creating an open PR as a way of working through my ToDo list

Currently, the code will create minimal FeatureContainer, ProteinContainer, and GenomeAnnotation objects, as individual JSON files.

ToDo:
1) Fasta to Assembly, assembly_reference, and actual dna_sequence/translation/amino_acid_sequences needed, as extracted using the GFF locations
2) Interfeature relationships as explicitly stated in the GFF "attributes" column
3) AnnotationQuality object
4) Saving in workspace
5) Taxonomy

GFF format references:
http://gmod.org/wiki/GFF3
http://www.sequenceontology.org/gff3.shtml

### CODE REVIEW

**Comment by samseaver** [comment]
Updated ToDo:

1) Check CDS ordering, generate amino-acid sequences for protein container
2) Extract timestamps from Phytozome fasta descriptions for each contig
3) Feature/Protein aliases
4) Interfeature relationships
5) Taxonomy
6) Saving in workspace
7) AnnotationQuality

**Comment by samseaver** [comment]
Updated ToDo:

1) Check CDS ordering, generate amino-acid sequences for protein container
2) Extract timestamps from Phytozome fasta descriptions for each contig
3) Taxonomy
4) Update correct set of locations in mRNA based on exons (currently testing on file without exons)
4) Saving in workspace
5) AnnotationQuality

**Comment by samseaver** [comment]
Updated ToDo:

1) Check CDS ordering, generate amino-acid sequences for protein container
2) Extract timestamps from Phytozome fasta descriptions for each contig
3) Taxonomy mapping (correct taxonomy ref now generated from hard-coded organism name)
4) Update correct set of locations in mRNA based on exons (currently testing on file without exons)
5) Compliance with GFF from Ensembl ("transcript"), RNA-Seq pipeline, and GFF downloader
6) Upload GFF to shock and add GFF handle (optional and ignored for now)
7) AnnotationQuality

**Comment by samseaver** [comment]
@mlhenderson Can you merge this PR? The script as it is will now successfully run, loading all containers and GenomeAnnotation object into workspace, and I'd like to have a commit ready in the develop branch for demo purposes, issues notwithstanding.

It can be run as such:

```./trns_transform_GFF_Fasta_Genome_to_KBaseGenomeAnnotations_GenomeAnnotation.py --input_gff_file ../../../t/test-gff/Athaliana_167_TAIR10.gene.gff3 --input_fasta_file ../../../t/test-gff/Athaliana_167_TAIR9.fa --workspace_name Transform_Test```

though the input files aren't added as they're big.

**Comment by mlhenderson** [comment]
Sure, I'll merge this in.  You probably will want to make everything but the GenomeAnnotation and Assembly objects hidden.

**Pull request merged**
