### PR TITLE
Fixed issue with taking entire fasta header as the key

### PR DESCRIPTION
**Pull request by jkbaumohl**

### CODE REVIEW

**Comment by mlhenderson** [comment]
This is to address KBASE-3041.  The same code was merged to develop and tested in CI, but since there are many other things in develop, we're patching this to master by itself to fix the issue with the production code.

**Comment by mlhenderson** [comment]
@scanon, @danielolson5, @kkellerlbl Merging this fix to master so that it can be in the queue for a production deploy.

**Comment by kkellerlbl** [comment]
Please make a jira ticket, assign to me, add Dan/Shane as watchers

-- 
Keith Keller
Physical Biosciences Division
(sent from mobile)

**Comment by jkbaumohl** [comment]
Ticket added
KBASE-3113 <https://atlassian.kbase.us/browse/KBASE-3113>

**Pull request merged**
