### PR TITLE
GFF/Fasta upload to GenomeAnnotation object

### PR DESCRIPTION
**Pull request by samseaver**
Opening a new PR, not to be merged yet, maintaining todo list here as before.

Done since last commit: protein translation and aggregated CDS (both need debugging)

1) Check CDS and Protein aggregation; Update mRNA locations
2) Incorporate Bio::Seq for fully functional translation (incl. gaps/unrecognized codons) along with translation tables
3) Testing of sequences against those found in Phytozome
3) Extract timestamps from Phytozome fasta descriptions for each contig
4) Taxonomy mapping (correct taxonomy ref now generated from hard-coded organism name)
5) Compliance with GFF from Ensembl ("transcript"), RNA-Seq pipeline, and GFF downloader
6) Hide all objects except for GenomeAnnotation and Assembly
7) Upload GFF to shock and add GFF handle (optional and ignored for now)
8) AnnotationQuality

### CODE REVIEW

**Comment by samseaver** [comment]
Updated ToDo:

1) Update mRNA locations
2) Insert warnings about incorrectly translated proteins (tiny number)
3) Incorporate Bio::Seq for fully functional translation (incl. gaps/unrecognized codons) along with translation tables
4) Testing of sequences against those found in Phytozome
5) Extract timestamps from Phytozome fasta descriptions for each contig
6) Compliance with GFF from Ensembl ("transcript"), RNA-Seq pipeline, and GFF downloader
7) Hide all objects except for GenomeAnnotation and Assembly
8) Upload GFF to shock and add GFF handle (optional and ignored for now)
9) AnnotationQuality

**Comment by samseaver** [comment]
couple of bug fixes brought up by processing all files, as it stands, the script can load all phytozome genomes. Probably biggest step made here is the move from my god-awful basic translation hack to the use of Biopython, which enables me to tackle dna and protein ambiguities consistently.

Other fixes include the inclusion of the genome version in the release field, the upload/use of the gff_handle_ref, and hiding of feature/protein containers

Updated ToDo:
1) Update mRNA locations
2) Insert warnings about incorrectly translated proteins (tiny number; reported by Biopython)
3) Testing of sequences against those found in Phytozome
4) Extract timestamps from Phytozome fasta descriptions for each contig
5) Compliance with GFF from Ensembl ("transcript"), RNA-Seq pipeline, and GFF downloader
6) AnnotationQuality

**Comment by samseaver** [comment]
I fixed how the locations and sequences are aggregated from UTRs and CDSs in mRNA feature objects, ahead of correctly generating the feature_lookup object. New ToDo:

Updated ToDo:
1) Generate feature_lookup object
2) Add gene model version numbers to workspace object identifiers
3) Testing of protein sequences against those found in Phytozome (update if needed)
4) Extract timestamps from Phytozome fasta descriptions for each contig
5) Compliance with other sources:
    - Ensembl ("transcript")
    - RNA-Seq pipeline
    - Microbial GFFs
    - KBase GFF downloader
    - GFFs that contain explicit exons
6) AnnotationQuality

**Comment by sychan** [comment]
This PR is over a year old, and still has a bunch of ToDo's listed. Please do not open a PR if it isn't ready to be merged.

**Pull request closed without merging**
