### PR TITLE
fix behavior for args --r_ori and --inl

### PR DESCRIPTION
**Pull request by levinas**
Set interleaved to 1 when the arg is provided.
Most of the difference shown is stripped whitespace due to my editor's default behavior.

### CODE REVIEW

**Comment by sjyoo** [comment]
Thanks for the commits... I'll propagate it to py_server branch where active development happening...

**Comment by levinas** [comment]
Thanks.

**Comment by olsonanl** [comment]
Do you need me to reissue my pull reqs against htat branch as well?

On Jan 14, 2015, at 2:18 PM, Fangfang Xia <notifications@github.com<mailto:notifications@github.com>> wrote:

Thanks.

**Comment by sjyoo** [comment]
Bob,

The script FangFang was changed was actively tested, so that I moved it right away…

If you want, then yes, please do it so…
but we should merge py_server version to master soon…

Thanks,
-SJ

On Jan 14, 2015, at 3:55 PM, olsonanl <notifications@github.com<mailto:notifications@github.com>> wrote:

Do you need me to reissue my pull reqs against htat branch as well?

On Jan 14, 2015, at 2:18 PM, Fangfang Xia <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:

Thanks.

**Pull request merged**
