### PR TITLE
Adding scripts for the transformation of ontology files

### PR DESCRIPTION
**Pull request by samseaver**

### CODE REVIEW

**Comment by mlhenderson** [comment]
What is the purpose of the core directory here?  Do you have other conversions that you expect will be using that code?  So far we have been including common "library" type code in the lib/ area.  If this is meant to be reused, it should reside there and not scripts/core/.

Can you add exception handling to your code?

Do you have tests and example input data?

**Comment by samseaver** [comment]
I've added ontology.t and Toy_Ontology.* test data, and also an eval statement for the system() command in the transform scripts.

I did initially look in lib, but it seemed like it was specifically for the transform handling code itself, but I moved it to the root lib directory. @levinas intends to address how it should be integrated properly but won't have time before the demo.

**Comment by mlhenderson** [comment]
@samseaver you should take a look at @cshenry code for FBA that uses try/catch instead of eval.  I'm concerned about "hidden" error conditions when code runs and we don't properly catch errors and report them out.  This is not only critical information for users, but also for debugging as a developer.

**Comment by cshenry** [comment]
IT’s real simple Sam.. literally almost replacing the “eval” with a “try”...

-- 
Chris Henry
Sent with Airmail

On April 13, 2016 at 6:05:51 PM, Matt Henderson (notifications@github.com) wrote:

@samseaver you should take a look at @cshenry code for FBA that uses try/catch instead of eval. I'm concerned about "hidden" error conditions when code runs and we don't properly catch errors and report them out. This is not only critical information for users, but also for debugging as a developer.

**Comment by samseaver** [comment]
Done

**Comment by mlhenderson** [comment]
I guess I'm wondering why we need to convert from .obo to JSON at all?  Does it provide a significant advantage?  Do we expect that these .obo files would be quite small?  Would you always have a 1:1 association between JSON and .obo?

What about just keeping the .obo files in Shock and maintaining handles from the JSON?  Then the JSON would be high level summary information, possibly some lookup info for the file contents.

The uploaders and downloaders also then become simpler.

I didn't literally mean lib/ for the obo.pl file, sorry for not being more clear.  The perl library code is under lib/Bio/KBase/Transform.  I suggested there because I assumed you would want to import it as a module, and this path is already available.  I do think that if code was written to be specifically linked to a particular set of uploads or downloads, that should live together, although there was always an assumption in there that everything was independent.  There are efforts to migrate plugins into modules created using the SDK.  So I would say try to keep your code as self contained as possible to make that transition easy.  If you need to duplicate obo.pl between an upload and download dir, it is ugly, but practical for now.  So I would say just move obo.pl to be local to the rest of your upload code here.

**Comment by cshenry** [comment]
Matt, what you propose seems like a significant departure from the data-modeling philosophy of this project. I know something along these lines is being discussed, but I didn't think any decisions had been made. I'm concerned that going this route would preclude the use of things like workspace subsetting to drive the population of dropdown in input forms etc. Ontology is an important type. It's one I feel we should handle rigorously and not just drop a handle to a file in the workspace. Also, we would have to port parsing code everywhere that the object is used, which seems bad. 

I understand that data-API will fix this issue, but until we have a rigorous data-API in place, I think we should continue with JSON typed objects, as this serves as a proxy for data-API by keeping data in a convenient pre-parsed form.

I also think the OBO format is not perfect. For example, it does not directly support a lineage or hierarchical organization for ontology terms, which is very important. While it is true that our first prototype spec is very close to a direct translation of OBO, I expect that over the course of our sprints, we will expand and tweak this spec to better handle our use cases, and while these will likely always be a 1-1 correspondence between obo and the Ontology dictionary, I expect the dictionary to be a richer object.

**Comment by mlhenderson** [comment]
I disagree that this is a significant departure because there has been no actual requirement for how to model data in KBase, only that it must have a representation as a KBase Type, which in some cases means a thin wrapper around a file (many cases of this) and in some cases all the data is in JSON docs (also many cases of this).  So I would say either approach has been accepted.  It has been relatively free form up to this point, since once you register a workspace module you can basically do whatever and there has been no actual formal review process, it has been ad hoc and inconsistently applied.

I am advising you based on our experience with GenomeAnnotation that going down this road of trying to store everything in JSON docs via the Workspace will later require a significant refactor or complete replacement.  JSON itself is not a bad thing, but it does have drawbacks, just like any other format, so we should be careful not to treat it as a one-size-fits-all approach to data.

Whether or not OBO is ideal, you will have to parse something no matter what.  There are other possible transformations of the data here.  It looks like a BigTable type storage might be nice to have here, but you could also just use tabular flat files on disk to get some of those benefits.  This would be easier overall to parse, subset, and index.  I would strongly recommend that your team at least consider this as an option.  The JSON should not be empty, but it also does not need to literally contain the primary data.  You should leverage the JSON for what it helps you with the most, mainly summarizing and visualizing.

If you *really* want to pursue the JSON only route, I'm not going to stop you in doing that.  I am just strongly advising against it.

**Comment by samseaver** [comment]
At this point in time, we've primarily concerned with being able to demonstrate work done by the Ontology team in the narrative-ci. We plan on making changes following feedback, but not before next Tuesday given that the test scripts worked, can you merge this PR.

**Comment by cshenry** [comment]
I see what you’re saying, but I just don’t see how we can make a landing page if we store the obo file directly in shock. Are we going to write JS code that pulls down the file and parses it in the browser? This is exactly what I meant by either needing a fully enabled data-API, or storing all the data needed to load the website in JSON.

And again, I think we will want to add additional relationships to the JSON that aren’t in the obo. So I see what you’re saying, but *right now* I think 100% JSON is the right way to go…  We may change our mind as we get deeper into this… and that’s fine. None of this is final… it’s just version 1.0. We have two more sprints coming on this topic.

On April 14, 2016 at 12:33:43 PM, Matt Henderson (notifications@github.com) wrote:
I disagree that this is a significant departure because there has been no actual requirement for how to model data in KBase, only that it must have a representation as a KBase Type, which in some cases means a thin wrapper around a file (many cases of this) and in some cases all the data is in JSON docs (also many cases of this). So I would say either approach has been accepted. It has been relatively free form up to this point, since once you register a workspace module you can basically do whatever and there has been no actual formal review process, it has been ad hoc and inconsistently applied.

I am advising you based on our experience with GenomeAnnotation that going down this road of trying to store everything in JSON docs via the Workspace will later require a significant refactor or complete replacement. JSON itself is not a bad thing, but it does have drawbacks, just like any other format, so we should be careful not to treat it as a one-size-fits-all approach to data.

Whether or not OBO is ideal, you will have to parse something no matter what. There are other possible transformations of the data here. It looks like a BigTable type storage might be nice to have here, but you could also just use tabular flat files on disk to get some of those benefits. This would be easier overall to parse, subset, and index. I would strongly recommend that your team at least consider this as an option. The JSON should not be empty, but it also does not need to literally contain the primary data. You should leverage the JSON for what it helps you with the most, mainly summarizing and visualizing.

If you really want to pursue the JSON only route, I'm not going to stop you in doing that. I am just strongly advising against it.

**Comment by mlhenderson** [comment]
@samseaver the only issue currently is the location of obo.pl, which I think should be easy to correct.

The common area for perl code would be under lib/Bio/KBase/Transform/.  Since you are calling this using a system call from the upload and download code, changing the path of this may cause problems for you.

I'm not actually trying to block your sprint activity.  The problem is you are attempting to do something that is not supported by the transform plugin model.  As soon as the deployment happens, you will lose the relative path to obo.pl and your execution will no longer function.

If you treat obo.pl as a library, you can place it under lib/Bio/KBase/Transform/ and you can use a standard perl import to bring that code in and call the functions you need.  If you treat obo.pl as a command line tool, that is currently not supported, not because you can't use command line tools, but because you are organizing and executing your code in a way that transform does not support.

I'm trying to save you some extra debugging work and frustration since I can see the problem already.

**Comment by samseaver** [comment]
Oh, I get it, the problem is the relative path. OK, given that @levinas is updating the code regularly in an external repository, I'll add copies of it into both the upload and download folders, and after the demo, we'll write a proper perl module.

**Pull request merged**
