### PR TITLE
GenometoGbk for objecto GenBank download

### PR DESCRIPTION
**Pull request by realmarcin**

### CODE REVIEW

**Comment by olsonanl** [comment]
The genome annotation service includes an export mechanism for a variety of formats, including genbank.

On Jan 7, 2015, at 5:21 PM, realmarcin <notifications@github.com<mailto:notifications@github.com>> wrote:

________________________________
You can merge this Pull Request by running

  git pull https://github.com/realmarcin/transform master

Or view, comment on, or merge it at:

  https://github.com/kbase/transform/pull/27

Commit Summary

  *   first version of Genome to Genbank for download
  *   added download

File Changes

  *   A src/us/kbase/genbank/GenometoGbk.java<https://github.com/kbase/transform/pull/27/files#diff-0> (321)

Patch Links:

  *   https://github.com/kbase/transform/pull/27.patch
  *   https://github.com/kbase/transform/pull/27.diff

**Comment by sjyoo** [comment]
That's nice... Does that directly work with Workspace?

**Comment by olsonanl** [comment]
No, and it shouldn't. It acts on genome objects.

On Jan 8, 2015, at 9:19 AM, sjyoo <notifications@github.com<mailto:notifications@github.com>> wrote:


That's nice... Does that directly work with Workspace?

**Comment by realmarcin** [comment]
Hi Bob,
Genome objects are stored in the workspace, right? And I assume the annotation service can't export for a user-uploaded genome?

Best,
Marcin

**Comment by olsonanl** [comment]
Genome objects can be stored anywhere; the workspace is just one place. An entity that wishes to export a genome can invoke the service to create the exportable form. It’s up to the caller to do something useful with that exportable form.

On Jan 8, 2015, at 11:04 AM, realmarcin <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Bob,
Genome objects are stored in the workspace, right? And I assume the annotation service can't export for a user-uploaded genome?

Best,
Marcin

**Comment by sjyoo** [comment]
Hi Marcin,

I guess Bob’s point was that since there is export function in annotation service,
if we wrap them up, then we could support various download functions quickly…

It doesn’t directly handle ws object and thus the script has to handle that…
and also if there is any additional related objects you want to dowload together,
I guess your download script need to take care of that as well.

Thanks,
-SJ

On Jan 8, 2015, at 12:04 PM, realmarcin <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Bob,
Genome objects are stored in the workspace, right? And I assume the annotation service can't export for a user-uploaded genome?

Best,
Marcin

**Comment by mlhenderson** [comment]
Right.  My concern is that if the object representation is based on the
annotation service typespec and not the workspace module typespec things
can easily get out of sync and you can have required fields in one place
and optional in another, etc.  There are other issues like how shock
references from workspace objects would be handled and that sort of thing.

Bob, can you just briefly describe how the annotation service method
works?  We pass in the json representation via rpc, and then you generate a
file or maybe files, and then where does it go and do you pass back a
download url or a job id that needs to be checked for completion and then
some other mechanism for retrieving the file?  I guess I'm not clear on
that part.

Maybe if you have an example that would illustrate it clearly.

**Comment by samseaver** [comment]
I should point out that Matt's concern is well-founded, we do know that the
Genome object generated by the annotation service does not match the
KBaseGenomes.Genome spec.  Chris' genome_annotation script for the NJS
takes the output genome and translates it for the workspace:

https://github.com/kbase/narrative_job_service/blob/master/scripts/njs-run-genome-annotation.pl

On Thu, Jan 8, 2015 at 11:28 AM, Matt Henderson <notifications@github.com>
wrote:

> Right. My concern is that if the object representation is based on the
> annotation service typespec and not the workspace module typespec things
> can easily get out of sync and you can have required fields in one place
> and optional in another, etc. There are other issues like how shock
> references from workspace objects would be handled and that sort of thing.
>
> Bob, can you just briefly describe how the annotation service method
> works? We pass in the json representation via rpc, and then you generate a
> file or maybe files, and then where does it go and do you pass back a
> download url or a job id that needs to be checked for completion and then
> some other mechanism for retrieving the file? I guess I'm not clear on
> that part.
>
> Maybe if you have an example that would illustrate it clearly.
>
>
> On Thu, Jan 8, 2015 at 9:10 AM, sjyoo <notifications@github.com> wrote:
>
> > Hi Marcin,
> >
> > I guess Bob’s point was that since there is export function in
> annotation
> > service,
> > if we wrap them up, then we could support various download functions
> > quickly…
> >
> > It doesn’t directly handle ws object and thus the script has to handle
> > that…
> > and also if there is any additional related objects you want to dowload
> > together,
> > I guess your download script need to take care of that as well.
> >
> > Thanks,
> > -SJ
> >
> > On Jan 8, 2015, at 12:04 PM, realmarcin <notifications@github.com
> <mailto:
> > notifications@github.com>> wrote:
> >
> > Hi Bob,
> > Genome objects are stored in the workspace, right? And I assume the
> > annotation service can't export for a user-uploaded genome?
> >
> > Best,
> > Marcin
> >
> >
> > > On Jan 8, 2015, at 07:26, olsonanl <notifications@github.com<mailto:
> > notifications@github.com>> wrote:
> > >
> > > No, and it shouldn't. It acts on genome objects.
> > >
> > > On Jan 8, 2015, at 9:19 AM, sjyoo <notifications@github.com<mailto:
> > notifications@github.com><mailto:notifications@github.com>> wrote:
> > >
> > >
> > > That's nice... Does that directly work with Workspace?
> > >
> > > —
> > > Reply to this email directly or view it on GitHub<
> > https://github.com/kbase/transform/pull/27#issuecomment-69193272>.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub.
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/kbase/transform/pull/27#issuecomment-69211251>.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/kbase/transform/pull/27#issuecomment-69212343>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kbase/transform/pull/27#issuecomment-69215367>.
>



-- 
Postdoctoral Fellow
Mathematics and Computer Science Division
Argonne National Laboratory
9700 S. Cass Avenue
Argonne, IL 60439

http://www.linkedin.com/pub/sam-seaver/0/412/168
samseaver@gmail.com
(773) 796-7144

"We shall not cease from exploration
And the end of all our exploring
Will be to arrive where we started
And know the place for the first time."
   --T. S. Eliot

**Comment by olsonanl** [comment]
if the workspace is going to be using the genome annotation service and storing such genome objects then it needs to have that typepsec available to the users. If the narrative can’t use the native types you’ll need to make such translation a universally available thing.

On Jan 8, 2015, at 11:33 AM, samseaver <notifications@github.com<mailto:notifications@github.com>> wrote:

I should point out that Matt's concern is well-founded, we do know that the
Genome object generated by the annotation service does not match the
KBaseGenomes.Genome spec. Chris' genome_annotation script for the NJS
takes the output genome and translates it for the workspace:

https://github.com/kbase/narrative_job_service/blob/master/scripts/njs-run-genome-annotation.pl

On Thu, Jan 8, 2015 at 11:28 AM, Matt Henderson <notifications@github.com<mailto:notifications@github.com>>
wrote:

> Right. My concern is that if the object representation is based on the
> annotation service typespec and not the workspace module typespec things
> can easily get out of sync and you can have required fields in one place
> and optional in another, etc. There are other issues like how shock
> references from workspace objects would be handled and that sort of thing.
>
> Bob, can you just briefly describe how the annotation service method
> works? We pass in the json representation via rpc, and then you generate a
> file or maybe files, and then where does it go and do you pass back a
> download url or a job id that needs to be checked for completion and then
> some other mechanism for retrieving the file? I guess I'm not clear on
> that part.
>
> Maybe if you have an example that would illustrate it clearly.
>
>
> On Thu, Jan 8, 2015 at 9:10 AM, sjyoo <notifications@github.com<mailto:notifications@github.com>> wrote:
>
> > Hi Marcin,
> >
> > I guess Bob’s point was that since there is export function in
> annotation
> > service,
> > if we wrap them up, then we could support various download functions
> > quickly…
> >
> > It doesn’t directly handle ws object and thus the script has to handle
> > that…
> > and also if there is any additional related objects you want to dowload
> > together,
> > I guess your download script need to take care of that as well.
> >
> > Thanks,
> > -SJ
> >
> > On Jan 8, 2015, at 12:04 PM, realmarcin <notifications@github.com<mailto:notifications@github.com>
> <mailto:
> > notifications@github.com<mailto:notifications@github.com>>> wrote:
> >
> > Hi Bob,
> > Genome objects are stored in the workspace, right? And I assume the
> > annotation service can't export for a user-uploaded genome?
> >
> > Best,
> > Marcin
> >
> >
> > > On Jan 8, 2015, at 07:26, olsonanl <notifications@github.com<mailto:notifications@github.com><mailto:
> > notifications@github.com<mailto:notifications@github.com>>> wrote:
> > >
> > > No, and it shouldn't. It acts on genome objects.
> > >
> > > On Jan 8, 2015, at 9:19 AM, sjyoo <notifications@github.com<mailto:notifications@github.com><mailto:
> > notifications@github.com<mailto:notifications@github.com>><mailto:notifications@github.com>> wrote:
> > >
> > >
> > > That's nice... Does that directly work with Workspace?
> > >
> > > —
> > > Reply to this email directly or view it on GitHub<
> > https://github.com/kbase/transform/pull/27#issuecomment-69193272>.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub.
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/kbase/transform/pull/27#issuecomment-69211251>.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/kbase/transform/pull/27#issuecomment-69212343>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kbase/transform/pull/27#issuecomment-69215367>.
>



--
Postdoctoral Fellow
Mathematics and Computer Science Division
Argonne National Laboratory
9700 S. Cass Avenue
Argonne, IL 60439

http://www.linkedin.com/pub/sam-seaver/0/412/168
samseaver@gmail.com<mailto:samseaver@gmail.com>
(773) 796-7144

"We shall not cease from exploration
And the end of all our exploring
Will be to arrive where we started
And know the place for the first time."
--T. S. Eliot

**Comment by samseaver** [comment]
The workspace specs are collectively found in
http://narrative.kbase.us/functional-site/#/spec/storage/0

As far as I know, Chris' code is the first time when such an asynchrony
occurs, i.e., for the new interface, we haven't had any other attempts to
load genomes from the annotation service.


On Thu, Jan 8, 2015 at 11:39 AM, olsonanl <notifications@github.com> wrote:

> if the workspace is going to be using the genome annotation service and
> storing such genome objects then it needs to have that typepsec available
> to the users. If the narrative can’t use the native types you’ll need to
> make such translation a universally available thing.
>
> On Jan 8, 2015, at 11:33 AM, samseaver <notifications@github.com<mailto:
> notifications@github.com>> wrote:
>
> I should point out that Matt's concern is well-founded, we do know that
> the
> Genome object generated by the annotation service does not match the
> KBaseGenomes.Genome spec. Chris' genome_annotation script for the NJS
> takes the output genome and translates it for the workspace:
>
>
> https://github.com/kbase/narrative_job_service/blob/master/scripts/njs-run-genome-annotation.pl
>
> On Thu, Jan 8, 2015 at 11:28 AM, Matt Henderson <notifications@github.com
> <mailto:notifications@github.com>>
> wrote:
>
> > Right. My concern is that if the object representation is based on the
> > annotation service typespec and not the workspace module typespec things
> > can easily get out of sync and you can have required fields in one place
> > and optional in another, etc. There are other issues like how shock
> > references from workspace objects would be handled and that sort of
> thing.
> >
> > Bob, can you just briefly describe how the annotation service method
> > works? We pass in the json representation via rpc, and then you generate
> a
> > file or maybe files, and then where does it go and do you pass back a
> > download url or a job id that needs to be checked for completion and
> then
> > some other mechanism for retrieving the file? I guess I'm not clear on
> > that part.
> >
> > Maybe if you have an example that would illustrate it clearly.
> >
> >
> > On Thu, Jan 8, 2015 at 9:10 AM, sjyoo <notifications@github.com<mailto:
> notifications@github.com>> wrote:
> >
> > > Hi Marcin,
> > >
> > > I guess Bob’s point was that since there is export function in
> > annotation
> > > service,
> > > if we wrap them up, then we could support various download functions
> > > quickly…
> > >
> > > It doesn’t directly handle ws object and thus the script has to handle
> > > that…
> > > and also if there is any additional related objects you want to
> dowload
> > > together,
> > > I guess your download script need to take care of that as well.
> > >
> > > Thanks,
> > > -SJ
> > >
> > > On Jan 8, 2015, at 12:04 PM, realmarcin <notifications@github.com
> <mailto:notifications@github.com>
> > <mailto:
> > > notifications@github.com<mailto:notifications@github.com>>> wrote:
> > >
> > > Hi Bob,
> > > Genome objects are stored in the workspace, right? And I assume the
> > > annotation service can't export for a user-uploaded genome?
> > >
> > > Best,
> > > Marcin
> > >
> > >
> > > > On Jan 8, 2015, at 07:26, olsonanl <notifications@github.com<mailto:
> notifications@github.com><mailto:
> > > notifications@github.com<mailto:notifications@github.com>>> wrote:
> > > >
> > > > No, and it shouldn't. It acts on genome objects.
> > > >
> > > > On Jan 8, 2015, at 9:19 AM, sjyoo <notifications@github.com<mailto:
> notifications@github.com><mailto:
> > > notifications@github.com<mailto:notifications@github.com>><mailto:
> notifications@github.com>> wrote:
> > > >
> > > >
> > > > That's nice... Does that directly work with Workspace?
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub<
> > > https://github.com/kbase/transform/pull/27#issuecomment-69193272>.
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/kbase/transform/pull/27#issuecomment-69211251>.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/kbase/transform/pull/27#issuecomment-69212343>.
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/kbase/transform/pull/27#issuecomment-69215367>.
> >
>
>
>
> --
> Postdoctoral Fellow
> Mathematics and Computer Science Division
> Argonne National Laboratory
> 9700 S. Cass Avenue
> Argonne, IL 60439
>
> http://www.linkedin.com/pub/sam-seaver/0/412/168
> samseaver@gmail.com<mailto:samseaver@gmail.com>
> (773) 796-7144
>
> "We shall not cease from exploration
> And the end of all our exploring
> Will be to arrive where we started
> And know the place for the first time."
> --T. S. Eliot
>
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/kbase/transform/pull/27#issuecomment-69216123>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kbase/transform/pull/27#issuecomment-69217086>.
>



-- 
Postdoctoral Fellow
Mathematics and Computer Science Division
Argonne National Laboratory
9700 S. Cass Avenue
Argonne, IL 60439

http://www.linkedin.com/pub/sam-seaver/0/412/168
samseaver@gmail.com
(773) 796-7144

"We shall not cease from exploration
And the end of all our exploring
Will be to arrive where we started
And know the place for the first time."
   --T. S. Eliot

**Comment by olsonanl** [comment]
I meant to do this as a pull req but had the wrong repo checked out, apologies. in any event I’ve commited a set of eight transform scripts that use RASTtk to generate exports from KBase genome objects:

https://github.com/kbase/transform/commit/8a226187dbac82fa8fc764abf43f1dc007df9d29

—bob

On Jan 8, 2015, at 11:39 AM, Olson, Robert D. <olson@mcs.anl.gov<mailto:olson@mcs.anl.gov>> wrote:

if the workspace is going to be using the genome annotation service and storing such genome objects then it needs to have that typepsec available to the users. If the narrative can’t use the native types you’ll need to make such translation a universally available thing.

On Jan 8, 2015, at 11:33 AM, samseaver <notifications@github.com<mailto:notifications@github.com>> wrote:

I should point out that Matt's concern is well-founded, we do know that the
Genome object generated by the annotation service does not match the
KBaseGenomes.Genome spec. Chris' genome_annotation script for the NJS
takes the output genome and translates it for the workspace:

https://github.com/kbase/narrative_job_service/blob/master/scripts/njs-run-genome-annotation.pl

On Thu, Jan 8, 2015 at 11:28 AM, Matt Henderson <notifications@github.com<mailto:notifications@github.com>>
wrote:

> Right. My concern is that if the object representation is based on the
> annotation service typespec and not the workspace module typespec things
> can easily get out of sync and you can have required fields in one place
> and optional in another, etc. There are other issues like how shock
> references from workspace objects would be handled and that sort of thing.
>
> Bob, can you just briefly describe how the annotation service method
> works? We pass in the json representation via rpc, and then you generate a
> file or maybe files, and then where does it go and do you pass back a
> download url or a job id that needs to be checked for completion and then
> some other mechanism for retrieving the file? I guess I'm not clear on
> that part.
>
> Maybe if you have an example that would illustrate it clearly.
>
>
> On Thu, Jan 8, 2015 at 9:10 AM, sjyoo <notifications@github.com<mailto:notifications@github.com>> wrote:
>
> > Hi Marcin,
> >
> > I guess Bob’s point was that since there is export function in
> annotation
> > service,
> > if we wrap them up, then we could support various download functions
> > quickly…
> >
> > It doesn’t directly handle ws object and thus the script has to handle
> > that…
> > and also if there is any additional related objects you want to dowload
> > together,
> > I guess your download script need to take care of that as well.
> >
> > Thanks,
> > -SJ
> >
> > On Jan 8, 2015, at 12:04 PM, realmarcin <notifications@github.com<mailto:notifications@github.com>
> <mailto:
> > notifications@github.com<mailto:notifications@github.com>>> wrote:
> >
> > Hi Bob,
> > Genome objects are stored in the workspace, right? And I assume the
> > annotation service can't export for a user-uploaded genome?
> >
> > Best,
> > Marcin
> >
> >
> > > On Jan 8, 2015, at 07:26, olsonanl <notifications@github.com<mailto:notifications@github.com><mailto:
> > notifications@github.com<mailto:notifications@github.com>>> wrote:
> > >
> > > No, and it shouldn't. It acts on genome objects.
> > >
> > > On Jan 8, 2015, at 9:19 AM, sjyoo <notifications@github.com<mailto:notifications@github.com><mailto:
> > notifications@github.com<mailto:notifications@github.com>><mailto:notifications@github.com>> wrote:
> > >
> > >
> > > That's nice... Does that directly work with Workspace?
> > >
> > > —
> > > Reply to this email directly or view it on GitHub<
> > https://github.com/kbase/transform/pull/27#issuecomment-69193272>.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub.
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/kbase/transform/pull/27#issuecomment-69211251>.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/kbase/transform/pull/27#issuecomment-69212343>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kbase/transform/pull/27#issuecomment-69215367>.
>



--
Postdoctoral Fellow
Mathematics and Computer Science Division
Argonne National Laboratory
9700 S. Cass Avenue
Argonne, IL 60439

http://www.linkedin.com/pub/sam-seaver/0/412/168
samseaver@gmail.com<mailto:samseaver@gmail.com>
(773) 796-7144

"We shall not cease from exploration
And the end of all our exploring
Will be to arrive where we started
And know the place for the first time."
--T. S. Eliot

**Pull request merged**
